### ISSUE TITLE
OTN control plane slicing

### ISSUE THREAD

**Issue by YunbinXu** [ietf-ccamp-wg/ietf-ccamp-yang-otn-slicing#10]
[OTN control plane slicing usecase.pptx](https://github.com/aguoietf/ietf-ccamp-yang-otn-slicing/files/6564786/OTN.control.plane.slicing.usecase.pptx)

**Comment by sergiobelotti** [comment]
> In the case of multi domain interworking, if the control planes of different domain need to be interoperable, do these control plane functions need to be sliced.

The problem you have in mind is only for multi-domain and interoperable case, or it can be envisaged also in single domain in case of multiple transport slice instance ?

**Comment by YunbinXu** [comment]
In single domain case, the control plane function for each transport slice can be configured by the OTN-PNC, it may not be perceived by the upper-layer controller, that needs to be discussed?



--------------------------------------------------------------------------------
Yunbin Xu   徐云斌 
宽带网络研究部
中国信息通信研究院（工业与信息化部电信研究院）技术与标准研究所
 
Research Institute of Telecommunications Transmission (RITT),
China Academy of Information Communications Technology(CAICT), MIIT
 
TEL: 86-18601328841，86-10-62300112
E-mail: ***@***.***  
--------------------------------------
 
From: sergiobelotti
Date: 2021-06-16 17:49
To: aguoietf/ietf-ccamp-yang-otn-slicing
CC: YunbinXu; Author
Subject: Re: [aguoietf/ietf-ccamp-yang-otn-slicing] OTN control plane slicing (#10)
In the case of multi domain interworking, if the control planes of different domain need to be interoperable, do these control plane functions need to be sliced.
The problem you have in mind is only for multi-domain and interoperable case, or it can be envisaged also in single domain in case of multiple transport slice instance ?

**Comment by aguoietf** [comment]
1. MPI (no cp sf considered, VN type 2 only, VN type 1 is already supported)
2. OTN SC NBI (no cp sf considered, VN type 1 & 2)
3. OTN SC NBI & SBI with cp sf considered. It could be a generic framework to request for sf. Needs to align with the IETF NSC work.

**Comment by aguoietf** [comment]
The Network Slice NBI YANG defines the specification of network service function which can be used by OTN-SC to request for control plane service function within an OTN slice.

        |        +--rw steering-constraints
        |           +--rw path-constraints
        |           +--rw service-function

**Comment by aguoietf** [comment]
Closed due to missing requirements from the NS framework and operators. Will reopen when demands are seen.
