### ISSUE TITLE
Should node-id, tp-id and link-id be URI or string?

### ISSUE THREAD

**Issue by italobusi** [ietf-ccamp-wg/ietf-ccamp-yang-otn-slicing#18]
See:

https://github.com/aguoietf/ietf-ccamp-yang-otn-slicing/pull/16#discussion_r732204452

https://github.com/aguoietf/ietf-ccamp-yang-otn-slicing/pull/16#discussion_r732204507

https://github.com/aguoietf/ietf-ccamp-yang-otn-slicing/pull/16#discussion_r732204709

**Comment by aguoietf** [comment]
Need  to discuss with network slice NBI YANG team to decide the format of network topology.

**Comment by aguoietf** [comment]
Closed by the fact that network slice topology is now defined outside the scope of this draft and is augmenting RFC8345 (network topology)
