### ISSUE TITLE
Relationship between an OTN slice and an Abstract (TE) Topology

### ISSUE THREAD

**Issue by aguoietf** [ietf-ccamp-wg/ietf-ccamp-yang-otn-slicing#30]
Clarify the relationship between an OTN slice and an Abstract (TE) Topology

[mail thread](https://mailarchive.ietf.org/arch/msg/ccamp/l1EDpQ3eIsW86sBETWggeNrQDQ4/)

**Comment by sergiobelotti** [comment]
I suggest this piece of text , to be put just at the beginning of section 3 .

"An IETF Network Slice Service interface is permitting a customer to express requirements for a particular slice specifying what is required and not how this can be achieved. This is typical characteristic of slicing in which the customer view of a slice is abstract and based on a logical abstract topology. 
Abstract topology is defined in RFC8453, as composed by abstract node and abstract link as defined in RFC 7926, providing allocation of resources and being able to convey  to the client characteristics related to the logical network helping client to make proper TE decision , e.g for path computation. 
Network slice includes abstract topology service adding the capability to steer the performance network indicator (SLI) towards the committed SLOs permitting  the client to use logical network as a stable and reliable physical network."
