### ISSUE TITLE
How does OTN slice support p2p, p2mp connectivity constructs

### ISSUE THREAD

**Issue by aguoietf** [ietf-ccamp-wg/ietf-ccamp-yang-otn-slicing#33]
In case of OTN slicing where the connectivity constructs defined by the NS framework,  such as P2MP, MP2MP will come from?
[mail thread](https://mailarchive.ietf.org/arch/msg/ccamp/l1EDpQ3eIsW86sBETWggeNrQDQ4/)

**Comment by sergiobelotti** [comment]
About this topic please consider the proposal made by Xufeng , see https://mailarchive.ietf.org/arch/msg/teas/dX59xP6Z7-2bOHfMjv_p6XhV21M/

**Comment by aguoietf** [comment]
Add descriptions for OTN slicing to support P2P/P2MP and the limitation in support MP2MP.

**Comment by aguoietf** [comment]
Specifying P2P, P2MP and MP2MP is defined by the network slice NBI YANG model.
MP2MP is replaced by any-to-any (A2A) construct
The constructs are described in Section 3.2.  IETF Network Slice Service

For OTN there may be technology-specific attributes needed for P2MP and A2A due to data plane restrictions.
