### ISSUE TITLE
Applicability of NRP to OTN slicing

### ISSUE THREAD

**Issue by italobusi** [ietf-ccamp-wg/ietf-ccamp-yang-otn-slicing#41]
NRP concept is introduced in section 6 of https://datatracker.ietf.org/doc/html/draft-ietf-teas-ietf-network-slices-10 to support the realization of IETF network slices

At the first glance, the concept looks similar to the "marking" of OTN resources described in section 4.1 of https://datatracker.ietf.org/doc/html/draft-ietf-ccamp-yang-otn-slicing-01

However, further investigation is required to understand whether NRP is a mandatory construct for IETF network slice realization and whether the NRP concept really matches the description in section 4.1 of https://datatracker.ietf.org/doc/html/draft-ietf-ccamp-yang-otn-slicing-01, in particular considering other YANG models being proposed in TEAS WG for the NRP YANG models

**Comment by italobusi** [comment]
This is the list of drafts in TEAS WG dealing with the NRP YANG model:

- https://datatracker.ietf.org/doc/html/draft-wd-teas-nrp-yang-00: this draft describes a YANG model for NRP and clearly states that it is a network configuration model (thus applicable between the NSC and the underlay network controller)
- https://datatracker.ietf.org/doc/html/draft-bestbar-teas-yang-nrp-policy-00: this draft describes a YANG model to configure the NRP policies to be used to instantiate NRP:
  - The applicability of this YANG model is not very clear but it references https://datatracker.ietf.org/doc/html/draft-bestbar-teas-ns-packet-08
  - The NRP policy depends on the configuration of topology filters defined in https://datatracker.ietf.org/doc/html/draft-bestbar-teas-yang-topology-filter-03

**Comment by aguoietf** [comment]
According to the discussion today here are my thoughts regarding NRP for OTN slicing:

NRP (Network Resource Partition) is a construct internal to the NSC to facilitate the mapping of a network slice to the underlay network. An NRP is a collection of resources identified in the underlay network and, although not required, may be represented as a network topology. The relationship between network slices and NRPs is M:N, meaning that multiple network slices can be created within the same NRP, and different connectivity constructs of a network slice can be mapped to separate NRPs.

An NRP may be used to address the scalability issue in packet networks, where there will be large amount of control and data plane states that need to be stored and programmed in a router if network slices are mapped directly to the router.  OTN resources are much more coarse granular (current ODU time slot granularity is ODU0~ODUCn, with the possibility to go lower in the future for sub-1G) and resources are usually abstracted within a single topology for a single OTN domain. The Use of NRP for OTN slicing is therefore neither eminent nor mandatory. 

There are a few options for an OTN-SC to use (or not use) NRP:
The OTN-SC may map an OTN slice directly onto the underlay TE topology received from the PNC. 
The OTN-SC may map an OTN slice to an NRP, which is 1:1 mapped to the underlay TE topology received from the PNC.
The OTN-SC may map an OTN slice to an NRP, which is an abstract TE topology created on top of the underlay TE topology. In this case there can be multiple NRPs (abstract TE topologies) created from the underlay TE topology.

In either of the options, the same MPI interface defined in this draft can be used at the OTN-SC SBI (MPI).

**Comment by sergiobelotti** [comment]
> I agree on most of your comment. I would add that the relationship between connectivity-construct and NRP resources in N:1 , and that a single connectivity construct is mapped to only one NRP. In the definition of NRP is also present the filter-topology that in my view is producing an abstract  virtual topology as we have in section 4.1.1 in our draft.
Following this thought I think the the third option you describe for OTN-SC would be perfect in line with filter topology usage of figure 4 of https://datatracker.ietf.org/doc/html/draft-ietf-teas-ietf-network-slices-10
So I do not think we should make particular actions with respect NRP in our OTN context.

**Comment by italobusi** [comment]
Slides updated during the call today: [otn-nrp-options-01.pptx](https://github.com/ietf-ccamp-wg/ietf-ccamp-yang-otn-slicing/files/8680810/otn-nrp-options-01.pptx)

**Comment by aguoietf** [comment]
Text proposal for NRP descriptions and diagrams:


4. Realizing OTN Slices

>[I-D.ietf-teas-ietf-network-slices] introduces a mechanism for an IETF network slice controller to realize network slices by constructing Network Resource Partitions (NRP). A NRP is a collection of resources identified in the underlay network to facilitate the mapping of network slices onto available network resources. An NRP is a scope view of a topology and may be considered as a topology in its own right. Thus, in traffic-engineered (TE) networks including OTN, an NRP may be simply represented as an abstract TE tology defined by [RFC8795]. For OTN networks, An NRP may be respresented as an abstract OTN topology defined by [I-D.ietf-ccamp-otn-topo-yang]. 

>The NRP may be used to address the scalability issues where there may be considerable numbers of control and data plane states required to be stored and programmed if network slices are mapped directly to the underlay topology. NRP is internal to a network slice controller, and use of NRPs is optional yet could benefit a network slice realization in large-scale networks, including OTN networks. 

>Without using the NRP, the OTN-SC may map an OTN slice directly onto the underlay TE topology presented by the subtended network controller (MDSC or PNC). In this case the OTN-SC needs to color corresponding link resources of the underlay topology with a slice identififer and maintain the coloring in order to keep track of the mapping of OTN slices. The OTN-SC pushes the colored topology to the subtended MDSC or PNC using the MPI model defined in this draft.

>Alternatively, by using the NRP, an OTN slice is mapped to a NRP as an overlay abstract OTN TE topology on top of the underlay topology. The corresponding link resources allocated to the slice is encapsulated in and tracked using the abstract topology, thus eliminating the need of coloring links in the underlay topology. Multiple OTN slices may be mapped to the same NRP, and a single connectivity construct of the slice may be mapped to only one NRP, as per [I-D.ietf-teas-ietf-network-slices].

>Figure 4 illustrates the relationship between OTN slices and NRP.

~~~
         /---------------/      |            /---------------/
        /  --     --    /       |           /  --     --    /
       /  |N1|---|N3|  /        |          /  |N2|---|N3|  /
      /    --\    --  /         |         /    --     --  /
     /        \--    /          |        /         --/   /
    /         |N2|  /           |       /         |N4|  /
   / Slice 1   --  /            |      / Slice 2   --  /
  /------------<--/             |     /-----------<---/
               <                |                 <
 +-------------<----------------V-----------------<------------+
 |          /--<--------------/             /-----<-----------/|
 |         / /--\     /--\   /             / /--\     /--\   / |
 |        / |NE1 |---|NE2 | /             / |NE1 |   |NE2 | /  |
 |       /   \--/\  . \--/ /             /   \--/     \--/ /   |
 |      /       ..\ ........            /              /. /    |
 |     / /--\   . /--\   / .           / /--\     /--\/ ./     |
 |    / |NE3 |  .|NE4 | /  .          / |NE3 |---|NE4 | .      |
 |   /   \--/   . \--/ /   .         /   \--/  .  \--/ /.      |
 |  /  NRP Topology 1 /    .        /  NRP Topology 2 / .      |
 | /------------.----/     .       /-----------.-----/  .      |
 |              .......    .                   .        .      |
 |             /------.----.-----------------/ .        .      |
 |            / /--\  .    .     /--\       /  .        .      |
 |           / |NE1 |-.----v----|NE2 |     /   .        .      |
 |          /   ---/\ .         /\--/     /    .        .      |
 |         /   /     \v        /<........................      |
 |        / /-/\      \ /--\  /         /      .               |
 |       / |NE3 |------|NE4 |/         /       .               |
 |      /   \--/  ^     \--/          /        .               |
 |     /  Underlay.OTN TE Topology   /         .               |
 |    /-----------.-----------------/          .               |
 |                ..............................     OTN-SC    |
 +-------------------------------------------------------------+
                  |                         ^
                  |MPI                      |MPI
 +----------------V--------------------------------------------+
 |                                                             |
 |                       OTN MDSC/PNC                          |
 +-------------------------------------------------------------+
~~~

**Comment by italobusi** [comment]
**2022-05-26 OTN Slicing Call**

Agreed to provide similar text in the draft, with few comments:
- NE3 and NE1 can be removed from NRP topology 1 and NRP topology 2
- add some text about the need to "push down" the NRP configuration at the MPI toward the network controller (MDSC or PNC)
- to define the MPI YANG model as an NRP topology which augments the OTN topology model
- take into account the current proposed NRP definition for the framework document:

> An NRP is simply a collection of resources identified in the underlay network. The amount and granularity of resources allocated in different portions of an NRP can be flexible. Depends on the operator’s policy and the service requirements, some NRP realizations may build the NRPs with dedicated topologies, while some other realizations may allow shared topology for multiple NRPs, one possible case is that the entire underlay network topology is used by all the NRPs. Some realization might as well use single NRP only with the resources of the entire underlay network topology. 

The text review can continue through a PR

- [ ] @aguoietf : submit a PR with the proposed changes to the draft and MPI YANG model
